[package]
name = "adf-template"
version = "0.1.0"
edition = "2021"

[dependencies]
adf-template-macro = { path = "./adf-template-macro" }
htmltoadf = "0.1.7"
serde = { version = "1.0.160", features = ["derive"] }
tinytemplate = "1.2.1"
