[package]
name = "adf-template-macro"
version = "0.1.1"
edition = "2021"
description = "A macro for generating ADF from html templates"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.85", features = ["full"] }
quote = "1.0.14"
proc-macro2 = "1.0.36"
